### PR TITLE
39 add like button to eventdetailsscreen

### PR DESCRIPTION
**Pull request by vanessa-covarrubias-nava**
# Description

What did you implemented/Why did you implemented this:

- Implemet like button component on EventDetailsScreen
- Users can like events and this events are save on firebase

- This implementation will create the favorites screen so users can see only the events they have liked and this events are saved on firebase with the userId. 

## Screenshots
image

### CODE REVIEW

**Review by ernesto2001-code — APPROVED** [review]
LGTM!

**Review by Antonio3veces3 — COMMENTED** [review]
Why the PR appears as Draft?

**Comment by vanessa-covarrubias-nava** [comment]
> Why the PR appears as Draft?

It's ready for review now

**Review by vrojas2 — APPROVED** [review]

**Review by Antonio3veces3 — APPROVED** [review]
Well done guys!

**Pull request merged**
