### PR TITLE
Create map component

### PR DESCRIPTION
**Pull request by ernesto2001-code**
# Description

- Create map component
- View the location of events with markers
- Get firebase data

## Screenshots
image

### CODE REVIEW

**Review by eCuevasCeballos — APPROVED** [review]
Great job Ernesto, you are the best!

**Review by eCuevasCeballos — APPROVED** [review]
LGTM!

**Comment by vanessa-covarrubias-nava** [comment]
Great!

**Review by vanessa-covarrubias-nava — APPROVED** [review]
Great!

**Pull request merged**
