### PR TITLE
Sprint5/issue #32 list and filter categories

### PR DESCRIPTION
**Pull request by eCuevasCeballos**
## Description

Show data from every event on EventDetails

Tasks
 - Show data from every event on EventDetails
 - Navigation should work fine
 - Get the information from firebase
 - Categories bar scroll
 - Categories bar design
 - Show events in events screen
 - Add events category in EventForm

## Design

WhatsApp Image 2024-03-25 at 17 57 15_856002e2
WhatsApp Image 2024-03-25 at 17 57 15_33a0386a

### CODE REVIEW

**Review by Antonio3veces3 — APPROVED** [review]
Well done!

**Review by ernesto2001-code — APPROVED** [review]
LGTM!

**Review by vanessa-covarrubias-nava — CHANGES_REQUESTED** [review]
Please check issues

**Review by vrojas2 — APPROVED** [review]

**Comment by eCuevasCeballos** [comment]
> Please check issues

Done!

**Review by vanessa-covarrubias-nava — APPROVED** [review]
Great work!

**Pull request merged**
